# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20171117_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programId', models.IntegerField(default=0)),
                ('bundleId', models.IntegerField(default=0)),
                ('firmwareId', models.IntegerField(default=0)),
                ('softwareId', models.IntegerField(default=0)),
            ],
        ),
    ]
